---
- hosts: localhost
  become: true
  vars:
    new_server_name: WP_server
    new_server_name2: Docker_server
    new_server_address: 10.12.0.10
    new_server_address2: 10.12.0.11

  tasks:
    - name: Install packages
      apt: 
        name: "{{ item }}"
        state: latest 
      loop: 
        - wget
        - build-essential
        - apache2
        - php
        - openssl
        - perl
        - make
        - php-gd
        - libgd-dev
        - libapache2-mod-php
        - libperl-dev
        - libssl-dev
        - daemon
        - autoconf
        - libc6-dev
        - libmcrypt-dev
        - libssl-dev
        - libnet-snmp-perl
        - gettext
        - unzip
        - rsyslog
      tags: [ 'setup' ]
        
    - name: Configure rsyslog server
      template:
        src: rsyslog_server.conf.j2
        dest: /etc/rsyslog.conf
        
    - name: Download Nagios core
      get_url:
        url: "https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.6.tar.gz" 
        dest: "/tmp/nagios.tar.gz"

    - name: Extract Nagios core
      ansible.builtin.unarchive:
        src: "/tmp/nagios.tar.gz"
        dest: "/tmp/"


    - name: Configure Nagios
      shell: |
         mkdir -p /usr/local/nagios/etc/servers
         touch /usr/local/nagios/etc/servers/client.cfg
         cd /tmp/nagios-4.4.6 && ./configure --with-httpd-conf=/etc/apache2/sites-available
         cd /tmp/nagioscore-nagios-4.4.14/
         sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
         make all
         make install-groups-users
         usermod -a -G nagios www-data
         make install install-daemoninit install-commandmode install-config install-webconf
         a2enmod rewrite
         a2enmod cgi
      
    - name: Add new server to nagios configuration
      blockinfile:
        path: /usr/local/nagios/etc/servers/client.cfg
        block: | 
          define host {
            use linux-server
            host_name {{ new_server_name }}
            address {{ new_server_address }}
            register 1
            hostgroups group_hosts
          }
          define host {
            use linux-server
            host_name {{ new_server_name2 }}
            address {{ new_server_address2 }}
            register 1 
            hostgroups group_hosts
          }
          define service {
            use local-service; Name of service template to use
            host_name {{ new_server_name }}, {{ new_server_name2 }}
            service_description Root Partition
            check_command check_local_disk!20%!10%!
          }
          define service {
            use local-service; Name of service template to use 
            host_name {{ new_server_name }}, {{ new_server_name2 }}
            service_description Current Users
            check_command check_local_users!20!50
          }
          define service { 
            use local-service; Name of service template to use 
            host_name {{ new_server_name }}, {{ new_server_name2 }}
            service_description Total Processes
            check_command check_local_procs!250!400!RSZDT
          }
          define service { 
            use local-service; Name of service template to use 
            host_name {{ new_server_name }}, {{ new_server_name2 }}
            service_description Check Load
            check_command check_local_load!5.0,4.0,3.0!10.0,6.0,4.0
          }
          define service {
           use local-service; Name of service template to use
           host_name {{ new_server_name }}, {{ new_server_name2 }}
           service_description Swap Usage
           check_command check_local_swap!20%!10%
          }
          define service {
           use local-service; Name of service template to use 
           host_name {{ new_server_name }}, {{ new_server_name2 }}
           service_description SSH
           check_command check_ssh
           notifications_enabled 0
          }
          define service { 
           use local-service; Name of service template to use
           host_name {{ new_server_name }}, {{ new_server_name2 }} 
           service_description HTTP
           check_command check_http
           notifications_enabled 0
          }
        backup: yes

    - name: Update monitoring server packages
      apt:
        update_cache: yes
        upgrade: yes
      
    - name: Update logserver packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Restart rsyslog server
      service: 
        name: rsyslog
        state: restarted
        
    - name: Restart Nagios service
      service:
        name: nagios
        state: restarted
        
    - name: Restart Apache server
      service: 
        name: apache2
        state: restarted
        
- name: Hosts config
  hosts: group_hosts
  become: true
  tasks:      
    - name: Install packages
      apt: 
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - 'nagios-nrpe-server'
        - 'nagios-plugins'
        - 'rsyslog'
      tags: [ 'setup' ]

    - name: configure NRPE
      template:
        src: nrpe.cfg.j2
        dest: /etc/nagios/nrpe.cfg
      
    - name: Configure rsyslog client
      template:
        src: rsyslog_client.conf.j2
        dest: /etc/rsyslog.conf
       
    - name: Restart Nagios nrpe
      service:
        name: nagios-nrpe-server
        state: restarted
       
    - name: Restart Rsyslog client
      service:
        name: rsyslog
        state: restarted

- name: Configure WordPress server
  hosts: 10.12.0.10
  become: true
  vars:
    wordpress_db_name: wp-db
    wordpress_db_user: wp-usr
    wordpress_url: /
    mysql_root_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34613535653435363939353537313535656336356533333838656630616665623062393832613437
      3537353738313165646432303666653232396430643635360a663632316664666661616435393362
      37663930386231633866656562626438323634373734356434623865663063376334626231303230
      6131353235646439650a353438353762623234643363333363363737616166363136383766326465
      3838
    wordpress_db_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37633230623739303662326532313664366364343163623537366137633262366138316436623236
      3664313538366632356164623838313134373061343838390a393232333563623166633964336536
      31373530663033636464386534326663616130666166636332613830646463643866323166316136
      6337366136643631660a356131333165623133393932313239396338323736626534356135653138
      3163
# use --ask-vault-pass because of this
  tasks:
    - name: Install packages
      apt: 
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - mysql-server
        - php
        - php-mysql
        - libapache2-mod-php
        - php-cli
        - php-gd
        - php-curl
        - php-xml
        - unzip
        - python3-pip
        - libmysqlclient-dev 
        - build-essential libssl-dev
        - libffi-dev 
        - python3-dev
      tags: [ 'setup' ]

    - name: install mysql python
      shell: "pip install mysql"
     
    - name: Configure MySQL root password
      debconf:
        name: 'mysql-server'
        question: 'mysql-server/root_password'
        value: '{{ mysql_root_password }}'
        vtype: 'password'

    - name: Configure MySQL root password (repeat)
      debconf:
        name: 'mysql-server'
        question: 'mysql-server/root_password_again'
        value: '{{ mysql_root_password }}'
        vtype: 'password'

    - name: Create MySQL database for WordPress
      mysql_db:
        name: '{{ wordpress_db_name }}'
        state: present
        login_user: root
        login_password: '{{ mysql_root_password }}'

    - name: Create MySQL user for WordPress
      mysql_user:
        name: '{{ wordpress_db_user }}'
        password: '{{ wordpress_db_password }}'
        priv: '{{ wordpress_db_name }}.*:ALL'
        state: present
        login_user: root
        login_password: '{{ mysql_root_password }}'

    - name: Download and extract WordPress
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'

    - name: Extract WordPress archive
      ansible.builtin.unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/html/'
        remote_src: yes
      ignore_errors: true
     

    - name: Set up WordPress configuration file
      template:
        src: wp-config.php.j2
        dest: '/var/www/html/wordpress/wp-config.php'
       
    - name: Harden Apache server
      template:
        src: apache_hardening.conf.j2
        dest: /etc/apache2/httpd.conf
       
    - name: Enable Apache hardening configuration
      shell: a2enconf hardening 
     
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

- name: Configure Docker server
  hosts: 10.12.0.11
  become: true
  vars:
    ansible_ssh_user: localadmin
  tasks:
    - name: Install packages
      apt: 
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      tags: [ 'setup' ]

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Add user to the docker group
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes
      become: true

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
